-- Insert para la tabla FARMACIA
INSERT INTO FARMACIA (FARMACIA_ID,NOMBRE) VALUES (2,"Farmacia tío Loyu e hijos");
INSERT INTO FARMACIA (FARMACIA_ID,NOMBRE) VALUES (3,"Farma & Co");
INSERT INTO FARMACIA (FARMACIA_ID,NOMBRE) VALUES (4,"Farmacia Sierra de Cazorla");
INSERT INTO FARMACIA (FARMACIA_ID,NOMBRE) VALUES (5,"Farmateca");
INSERT INTO FARMACIA (FARMACIA_ID,NOMBRE) VALUES (6,"Farma PEAL");

-- Insert para la tabla MEDICAMENTO

INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (2,20,"Ibuprofeno",1);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (3,30,"Biodramina",1);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (4,10,"Ibuprofeno",1);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (5,20,"Abelcet Concentrado",1);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (6,25,"Abrasone",1);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (7,18,"Aceltisteina",1);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (8,23,"Edunix",1);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (9,10,"Placitex",1);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (10,22,"Ibuprofeno",2);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (11,45,"Biodramina",2);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (12,15,"Ibuprofeno",2);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (13,33,"Abelcet Concentrado",2);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (14,20,"Ibuprofeno",3);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (15,30,"Biodramina",3);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (16,25,"Abrasone",3);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (17,18,"Aceltisteina",3);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (18,23,"Edunix",3);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (19,29,"Placitex",3);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (20,5,"Ibuprofeno",4);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (21,7,"Biodramina",4);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (22,15,"Ibuprofeno",4);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (23,32,"Abelcet Concentrado",4);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (24,6,"Abrasone",4);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (25,17,"Aceltisteina",4);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (26,8,"Edunix",4);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (27,100,"Placitex",4);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (28,20,"Ibuprofeno",5);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (29,23,"Edunix",5);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (30,20,"Ibuprofeno",1);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (31,30,"Biodramina",6);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (32,60,"Ibuprofeno",6);
INSERT INTO MEDICAMENTO (MEDICAMENTO_ID,CANTIDAD,NOMBRE,FARMACIA_ID) VALUES (33,20,"Abelcet Concentrado",6);